[site]
title = "Staple Homepage"
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "staple"
domain = "https://kilerd.github.io"
domain_root = "staple"
default_template = "article.html"

[hook]
before_build = [
    { dir="templates/staple/statics", command="lessc style.less style.css" }
]

[watch]
exclusive = [
    "templates/staple/statics/style.css",
]

[extra]
version = "0.3.1"