[site]
title = "Staple Homepage"
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "staple"
domain = "https://kilerd.github.io"
domain_root = "staple"

[[statics]]
from = "CNAME"
to = "CNAME"

[extra]
version = "0.2.0"
