[site]
title = "Staple Homepage"
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "staple"
index_data = "data/index.toml"

[url]
url = "https://kilerd.github.io/"
root = "staple/"
permalink = "{year}/{month}/{day}/{title}.html"

[rss]
enable = true
article_limited = 10

[pagination]
page_size = 10

[[pages]]
show_in_nav = true
nav_title = "ABOUTME"
file = "about.md"
template = "page.html"
data = "pages/about.toml"


[[statics]]
from = "CNAME"
to = "CNAME"

[extra]
version = "0.2.0"
