[site]
title = "Staple Homepage"
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "staple"
domain = "https://kilerd.github.io"
domain_root = "staple"
default_template = "article.html"

[[statics]]
from = "CNAME"
to = "CNAME"

[extra]
version = "0.2.0"


[hook]
before_build = [
    "ls",
#    { dir = "./data", command = "ls" },
    "ping www.baidu.com -c 10"
]