[site]
title = ""
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = +800
theme = "staple"

[url]
url = ""
root = ""
permalink = "{year}/{month}/{day}/{title}.html"

[pagination]
page_size = 10

[extra]