[site]
title = ""
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "rubble"

[url]
url = "localhost"
root = "/"
permalink = "{year}/{month}/{day}/{title}.html"

[pagination]
page_size = 10

[extra]
