name: Develop Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run cargo clean
        run: cargo clean
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1
      - name: Run Code Coverage
        run: |
          cargo tarpaulin --ciserver github-ci --coveralls $COVERALLS_REPO_TOKEN -- --test-threads 1
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}